Update electron.yaml

diff --git a/.github/workflows/electron.yaml b/.github/workflows/electron.yaml
--- a/.github/workflows/electron.yaml
+++ b/.github/workflows/electron.yaml
@@ -30,6 +30,24 @@ jobs:
             - name: Checkout code
               uses: actions/checkout@main
 
+            - name: Get version from package.json
+              id: get_version
+              run: |
+                  echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
+
+            - name: Get latest tag
+              id: get_tag
+              run: |
+                  latest_tag=$(git describe --tags --abbrev=0 || echo "")
+                  echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
+
+            - name: Check if package version matches latest tag
+              run: |
+                  if [ "${{ env.LATEST_TAG }}" == "v${{ env.PACKAGE_VERSION }}" ]; then
+                    echo "Error: Package version matches the latest tag. Please update the package version."
+                    exit 1
+                  fi
+
             - name: Set up Node.js
               uses: actions/setup-node@main
               with:
@@ -165,12 +183,11 @@ jobs:
                       fi
                   fi
                   echo "latest_tag=$new_tag" >> $GITHUB_ENV
-                  echo "new_tag=$new_tag"
 
             - name: Create tag
               run: |
-                  git tag ${{ env.new_tag }}
-                  git push origin ${{ env.new_tag }}
+                  git tag ${{ env.latest_tag }}
+                  git push origin ${{ env.latest_tag }}
 
             - name: Create GitHub release
               id: create_release
